// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    README: typeof import('./core/components/README.md')['default']
    TheCounter: typeof import('./core/components/TheCounter.vue')['default']
    TheFooter: typeof import('./core/components/TheFooter.vue')['default']
  }
}

export { }
